#!/bin/sh

# Setup the AWS Lambda Runtime Interface Emulator
# https://github.com/aws/aws-lambda-runtime-interface-emulator/
mkdir -p ~/.aws-lambda-rie && curl -Lo ~/.aws-lambda-rie/aws-lambda-rie \
    https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie-arm64 \
    && chmod +x ~/.aws-lambda-rie/aws-lambda-rie

# Start the Lambda shell container
docker run -d --rm \
    -p 9000:8080 \
    --name lambda-shell-runtime \
    --platform linux/arm64 \
    -v ~/.aws:/root/.aws:ro \
    --volume ~/.aws-lambda-rie:/aws-lambda \
    --entrypoint /aws-lambda/aws-lambda-rie \
    --env HANDLER="handler.hello" \
    lambda-shell-runtime:micro \
    /var/runtime/bootstrap



# Invoke test: basic curl request
curl -XPOST \
    "http://localhost:9000/2015-03-31/functions/function/invocations" \
    -d '{}'

# Invoke test using http-bin
http-bin -d '{}' \
    "http://localhost:9000/2015-03-31/functions/function/invocations"
