#!/bin/sh

set -ex

# Default config
PLATFORM="linux/arm64"
MODE="--load"
TAG="lambda-shell-runtime"
VERSION="${VERSION:-dev}"
VARIANTS="base tiny micro full"

# Parse arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --platform)
      PLATFORM="$2"
      shift 2
      ;;
    --tag)
      TAG="$2"
      shift 2
      ;;
    --push)
      MODE="--push"
      shift
      ;;
    --load)
      MODE="--load"
      shift
      ;;
    full|tiny|micro|base)
      VARIANTS="$1"
      shift
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

for VARIANT in $VARIANTS; do
  DOCKERFILE="./Dockerfile"
  TARGET="$VARIANT"

  [ "$VARIANT" = "base" ] && TARGET=""

  [ "$VARIANT" = "base" ] && MODE="--load"

  echo "Building $VARIANT ($DOCKERFILE) with platform $PLATFORM..."
  docker buildx build \
    --platform "$PLATFORM" \
    --secret id=github_token,env=GITHUB_TOKEN \
    --tag $TAG:$VARIANT \
    --file "$DOCKERFILE" \
    ${TARGET:+--target "$TARGET"} \
    $MODE \
    .

  if [ -n "$VERSION" ]; then
    echo "Tagging $TAG:$VARIANT-$VERSION"
    docker tag $TAG:$VARIANT $TAG:$VARIANT-$VERSION
  fi
done

