# FROM ghcr.io/ql4b/lambda-shell-runtime:0.1.0-develop.10-full
FROM lambda-shell-runtime:micro
# FROM ghcr.io/ql4b/lambda-shell-runtime:0.1.0-develop.10-slim

WORKDIR /var/task

COPY service.sh handler.sh