#!/bin/bash

source $(realpath $(dirname $0))/rrelay.sh

request='{"adults":1,"children":1,"infants":1,"teens":0,"origin":"NAP","destination":"BCN","dateOut":"2025-07-13"}'
echo $request >&2
correlation_id=$(uuidgen | tr '[:upper:]' '[:lower:]')
# export USER_AGENT=$(randua)


departureDate=$(echo "$request" | jq -r '.dateOut +"T00:00:00.000"')
# echo "$departureDate" >&2

flight=$(availability "$request" \
    | jq --arg dateOut "$departureDate" '.trips[].dates[]|select(.dateOut == $dateOut).flights|first|del(.segments)'
)
# {"faresLeft":4,"flightKey":"FR~  59~ ~~NAP~07/10/2025 15:40~BCN~07/10/2025 17:40~~","infantsLeft":16,"regularFare":{"fareKey":"VES4L3AY6V7QCEKP25YZQOZOZFWRY6UDQRC75USHLWWP46O6ECSN3JO4DDEUY7PI6ZAYZLISSNP4PT65R2P2ARTBKRII4CWGMYQKF4XU5WT37LIAC6LWDC332SPT64QR3GVVX53FTHOJNJMUUVQHXIUMHUVE6N3XE3O7NOLV4B4LZPUNAUC6U7O3ZSFR246HBE4CAXKCCXWOHC45UGVSGFR4WCXUGBKVKW54IAFFT6EXQYIWSKSFUHLX2ESS3AYRWPRKDLH22KKRDX7HDT4XRZEEJZMLX5BS2WQ6M5ORROOZJ3FMAWVPPDOP3GY742C2OZDU5IEDFB3YAFOJPHSTPDAIG3IW6YDTHMNCHGI","fares":[{"type":"ADT","amount":197.99,"count":1,"hasDiscount":false,"publishedFare":197.99,"discountInPercent":0,"hasPromoDiscount":false,"discountAmount":0.0,"hasBogof":false,"isPrime":false}]},"operatedBy":"","isSSIMLoad":false,"flightNumber":"FR 59","time":["2025-07-10T15:40:00.000","2025-07-10T17:40:00.000"],"timeUTC":["2025-07-10T13:40:00.000Z","2025-07-10T15:40:00.000Z"],"duration":"02:00"}
echo "$flight" | jq -c >&2

basketID=$(create_basket | jq -r '.data.createBasket.id')
# echo "basketId:$basketID" >&2
culture=$(dashed_market "$market")
# echo "$culture" >&2
variables=$(booking_variables "$basketID" "$request" "$flight")
# echo "$variables" | jq >&2
export JWT_HANDLER=$(mktemp)
create_booking "$variables" 
echo "$JWT" >&2
booking=$(commit_booking "$basketID" | jq  .data.commitBooking)
echo "$booking" | jq >&2
data=$(catalog_products "$basketID" "$JWT")
echo "$data" | jq >&2