#!/bin/sh
set -e

VERSION="$1"

echo "Publishing Docker images with version $VERSION"

for VARIANT in tiny slim full; do
  IMAGE="ghcr.io/ql4b/lambda-shell-base:$VARIANT"
  docker tag lambda-shell-base:$VARIANT "$IMAGE:$VERSION"
  docker tag lambda-shell-base:$VARIANT "$IMAGE:latest"
  docker push "$IMAGE:$VERSION"
  docker push "$IMAGE:latest"
done
