#!/bin/sh
set -euo pipefail

echo "Logging in to GitHub Container Registry..."
echo "${GITHUB_TOKEN:?Environment variable GITHUB_TOKEN not set}" | docker login ghcr.io -u "${GITHUB_USER:-$(whoami)}" --password-stdin

# Get version argument
VERSION="${1:-"dev"}"
BASE_IMAGE="ghcr.io/ql4b/lambda-shell-runtime"

echo "Publishing Docker images with version $VERSION"

# for VARIANT in tiny micro full; do
for VARIANT in tiny; do
  echo "Building and pushing $VARIANT image..."

    TAG="$VERSION-$VARIANT"
    docker tag lambda-shell-runtime:$VARIANT "$BASE_IMAGE:$TAG"
    docker tag lambda-shell-runtime:$VARIANT "$BASE_IMAGE:$VARIANT-latest"
    docker tag lambda-shell-runtime:$VARIANT "$BASE_IMAGE:$VARIANT"
    docker push "$BASE_IMAGE:$TAG"
    docker push "$BASE_IMAGE:$VARIANT-latest"
    docker push "$BASE_IMAGE:$VARIANT"

done
