#!/bin/sh
set -e

VERSION="$1"

echo "Publishing Docker images with version $VERSION"

for VARIANT in tiny slim full; do
  BASE_IMAGE="ghcr.io/ql4b/lambda-shell-base"
  TAG="$VERSION-$VARIANT"
  docker tag lambda-shell-base:$VARIANT "$BASE_IMAGE:$TAG"
  docker tag lambda-shell-base:$VARIANT "$BASE_IMAGE:$VARIANT-latest"
  docker push "$BASE_IMAGE:$TAG"
  docker push "$BASE_IMAGE:$VARIANT-latest"
done
