name: Build Base Image

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile'
      - 'runtime/**'
      - 'task/handler.sh'
      - '.github/workflows/build-base.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'runtime/**'
      - 'task/handler.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push base
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --provenance=false \
            --secret id=github_token,env=GITHUB_TOKEN \
            --target base \
            --tag ghcr.io/${{ github.repository_owner }}/lambda-shell-runtime:base \
            --push \
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}