name: Release

on:
  push:
    branches:
      - develop
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-arch Docker images
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: |
          echo "$GHCR_PAT" | docker login ghcr.io -u skunxicat --password-stdin

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/ql4b/lambda-shell-runtime:tiny-latest \
            -f tiny.Dockerfile . \
            --push

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/ql4b/lambda-shell-runtime:slim-latest \
            -f slim.Dockerfile . \
            --push

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/ql4b/lambda-shell-runtime:full-latest \
            -f Dockerfile . \
            --push
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}